#!/bin/bash

echo "🔧 Database Reset Solution for Coolify"
echo "======================================"
echo ""

echo "❌ Current Problem:"
echo "- Table 'ledfinebooking_product_appointment_slots' already exists"
echo "- Column 'code' not found in attribute_groups table"
echo "- Database structure is inconsistent"
echo ""

echo "🎯 SOLUTION: Reset Database Completely"
echo ""
echo "METHOD 1: Via Coolify Environment Variables"
echo "=========================================="
echo "1. Go to Coolify Environment Variables"
echo "2. Set: FORCE_FRESH_INSTALL=true"
echo "3. Deploy (this will drop ALL tables and recreate)"
echo "4. After successful deployment, set: FORCE_FRESH_INSTALL=false"
echo "5. Deploy again to prevent future resets"
echo ""

echo "METHOD 2: Manual Database Reset (if Method 1 doesn't work)"
echo "=========================================================="
echo "In Coolify terminal, run these commands:"
echo ""
echo "# 1. Connect to MySQL container"
echo "docker exec -it \$(docker ps --filter name=mysql -q) mysql -u ledfine_user_wagner -pledfine_Danydryan12* ledfine_db"
echo ""
echo "# 2. Drop all tables (CAREFUL!)"
echo "DROP DATABASE ledfine_db;"
echo "CREATE DATABASE ledfine_db;"
echo "exit"
echo ""
echo "# 3. Restart the application container"
echo "docker restart \$(docker ps --filter name=app -q)"
echo ""

echo "METHOD 3: Alternative - Use Different Database Name"
echo "==================================================="
echo "1. In Coolify Environment Variables:"
echo "   DB_DATABASE=ledfine_db_fresh"
echo "2. This will create a completely new database"
echo "3. Deploy"
echo ""

echo "⚠️  WARNING: All methods will DELETE existing data!"
echo "If you have important data, backup first:"
echo "docker exec \$(docker ps --filter name=mysql -q) mysqldump -u ledfine_user_wagner -pledfine_Danydryan12* ledfine_db > backup.sql"
echo ""

echo "🎯 Recommended: METHOD 1 (simplest)"
echo "Just toggle FORCE_FRESH_INSTALL=true, deploy, then set to false"