services:
  app:
    build: .
    image: ledfine/php:8.2-fpm
    working_dir: /var/www/app
    expose:
      - "9000"
    environment:
      COMPOSER_ALLOW_SUPERUSER: "1"
    volumes:
      - ./:/var/www
      - composer_cache:/tmp/composer
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pgrep php-fpm || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  webserver:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: ledfine/nginx:latest
    expose:
      - "80"
    volumes:
      - ./:/var/www
    depends_on:
      app:
        condition: service_started
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_DATABASE:-ledfine_db}
      MYSQL_USER: ${DB_USERNAME:-ledfine_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-ledfine_pass}
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p${MYSQL_ROOT_PASSWORD:-root} || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10

  node:
    image: node:20-alpine
    working_dir: /var/www/app
    volumes:
      - ./:/var/www
    profiles: ["dev"]

volumes:
  dbdata:
  composer_cache:
