FROM nginx:alpine

# Install curl for healthcheck
RUN apk --no-cache add curl

# Copy custom nginx configuration
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
