services:
  app:
    build: .
    image: ledfine/php:8.2-fpm
    working_dir: /var/www/app
    environment:
      COMPOSER_ALLOW_SUPERUSER: "1"
    volumes:
      - ./:/var/www
      - composer_cache:/tmp/composer
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  webserver:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: ledfine/nginx:latest
    expose:
      - "80"
    volumes:
      - ./:/var/www
    depends_on:
      app:
        condition: service_started
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost/healthz || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5

  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ledfine_db
      MYSQL_USER: ledfine_user
      MYSQL_PASSWORD: ledfine_pass
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10

  node:
    image: node:20-alpine
    working_dir: /var/www/app
    volumes:
      - ./:/var/www
    profiles: ["dev"]

volumes:
  dbdata:
  composer_cache:
