#!/bin/bash

echo "🔧 Fixing Coolify Environment Configuration"
echo "==========================================="
echo ""

echo "❌ Problems Found in env.prod.md:"
echo "1. CACHE_STORE=redis but 'Class Redis not found'"
echo "2. QUEUE_CONNECTION=redis but no Redis extension" 
echo "3. DB_HOST should match docker-compose service name"
echo "4. FORCE_FRESH_INSTALL=true causing constant DB resets"
echo ""

echo "✅ Required Coolify Environment Variable Changes:"
echo ""
echo "In Coolify, set these environment variables:"
echo ""
echo "# Database (already correct)"
echo "DB_HOST=db"
echo "DB_DATABASE=ledfine_db" 
echo "DB_USERNAME=ledfine_user_wagner"
echo "DB_PASSWORD=ledfine_Danydryan12*"
echo "DB_PREFIX=ledfine"
echo ""
echo "# Cache & Sessions (CRITICAL FIXES)"
echo "CACHE_STORE=file"
echo "SESSION_DRIVER=file"
echo "QUEUE_CONNECTION=sync"
echo ""
echo "# Remove problematic variables"
echo "FORCE_FRESH_INSTALL=false   # Or remove entirely"
echo ""
echo "# Redis (remove if Redis extension not working)"
echo "REDIS_CLIENT=predis"
echo "REDIS_HOST=redis"
echo ""

echo "📋 Steps to fix in Coolify:"
echo "1. Go to your application environment variables"
echo "2. Change CACHE_STORE from 'redis' to 'file'"
echo "3. Change SESSION_DRIVER to 'file' (if not already)"
echo "4. Change QUEUE_CONNECTION from 'redis' to 'sync'"
echo "5. Set FORCE_FRESH_INSTALL=false or remove it"
echo "6. Save and redeploy"
echo ""

echo "🎯 This should resolve the 'Class Redis not found' errors"
echo "   and stop the constant database conflicts."